Added ContextElements to json export
IncQueryLabs/mdk pull request #16
Opened 2022-07-04 14:19 UTC by zavadaarmin

2022-07-08 16:33 UTC, bergmanngabor requested changes
Well done, great job!

I have a few comments though.

2022-07-11 09:09 UTC, zavadaarmin commented on src/main/java/gov/nasa/jpl/mbee/mdk/fileexport/ElementContextProvider.java
> +		objectNode.put(MDKConstants.PROJECT_ID, iProject.getProjectID());
I thought about that, however, my thinking was that if the context elements spread like viruses, then the context set would massively outgrow the actual element set.

Maybe this could become a follow up issue, if we want to extend this functionality in the future.

2022-07-11 09:09 UTC, zavadaarmin commented on src/main/java/gov/nasa/jpl/mbee/mdk/fileexport/ElementContextProvider.java
> +                    // TODO: get attached project primary model as element
Yes, unfortunately I couldn't come up with a solution - I am open to suggestions

2022-07-11 09:11 UTC, zavadaarmin commented on src/main/java/gov/nasa/jpl/mbee/mdk/fileexport/ElementContextProvider.java
> +
My fear is that container would inflate the context set too much (see above comment)

2022-07-11 09:12 UTC, zavadaarmin commented on src/main/java/gov/nasa/jpl/mbee/mdk/fileexport/ElementContextProvider.java
> +    private enum FeatureContextAggregator {
I agree, this is an ugly solution.. However, I was not able to come up with a simple solution, that would not require massive refactor on the exporter side.

2022-07-11 10:03 UTC, bergmanngabor commented on src/main/java/gov/nasa/jpl/mbee/mdk/fileexport/ElementContextProvider.java
> +		objectNode.put(MDKConstants.PROJECT_ID, iProject.getProjectID());
Not really, since each element has at most _k_ container elements, where _k_ is the containment depth of the project.

But I am OK with leaving it for followup.

2022-07-11 10:05 UTC, bergmanngabor commented on src/main/java/gov/nasa/jpl/mbee/mdk/fileexport/ElementContextProvider.java
> +                    // TODO: get attached project primary model as element
ask the experts at the MBSE team for advice (i.e. MD-specific black magic)

2022-07-11 12:50 UTC, zavadaarmin commented on src/main/java/gov/nasa/jpl/mbee/mdk/fileexport/ElementContextProvider.java
> +		objectNode.put(MDKConstants.PROJECT_ID, iProject.getProjectID());
@debrecenics what do you think? This is basicly a 0-cost feature. However, FQN was explicitly required by LL, but that is also a 0-cost feature (as MD already calculates it)

2022-07-11 12:58 UTC, zavadaarmin commented on src/main/java/gov/nasa/jpl/mbee/mdk/fileexport/ElementContextProvider.java
> +                    // TODO: get attached project primary model as element
The good news tho: it seems there are no broken links, as each referenced model element is added to the context regardless - if this is true, than this code is safe to delete.

2022-07-13 07:05 UTC, zavadaarmin commented
We added a choice setting to choose which context level to use. The additional logic we talked about will be done in a followup issue.

2022-07-13 09:16 UTC, bergmanngabor approved these changes
Well done, almost LGTM.
I have a few very minor leftover comments that you can resolve on your own - there is no need for another review round.

2022-07-14 11:29 UTC, merged